### PR TITLE
Fix an assertion when building the clad benchmarks with clang18 on osx.

### PR DESCRIPTION
**Pull request by vgvassilev**
Unfortunately, it'd be difficult to come up with a test...

### CODE REVIEW

**Review by vaithak — APPROVED** [review]
Looks good.
But, given that we will improve the error or diagnostic messages in the future, maybe we can use `E->getBeginLoc` and `E->getEndLoc` instead of creating fake ones.

**Comment by vgvassilev** [comment]
> Looks good. But, given that we will improve the error or diagnostic messages in the future, maybe we can use `E->getBeginLoc` and `E->getEndLoc` instead of creating fake ones.

Until now we explicitly tried to use the fakeLoc approach to consistently annotate where we need to handle source locations in a non-crashing way. We could but that would point to the original function. Is that what you want here?

**Comment by vaithak** [comment]
> Until now we explicitly tried to use the fakeLoc approach to consistently annotate where we need to handle source locations in a non-crashing way. We could but that would point to the original function. Is that what you want here?

Although it would point to the original function. It will be really helpful for creating minimal reproducers from big functions. As, these location informations in the primal function will point to the line or location of the troublesome expression.

**Comment by vgvassilev** [comment]
> > Until now we explicitly tried to use the fakeLoc approach to consistently annotate where we need to handle source locations in a non-crashing way. We could but that would point to the original function. Is that what you want here?
> 
> Although it would point to the original function, it will be really helpful for creating minimal reproducers from big functions, as these location informations in the primal function will point to the line or location of the troublesome expression.

Ok. Let me change that. However, this comment is questioning our currently strategy here, right? If you agree we should open an issue where we suggest replacing all of the fake locations with ones pointing to the original function.

**Comment by vaithak** [comment]
> Ok. Let me change that. However, this comment is questioning our currently strategy here, right? If you agree we should open an issue where we suggest replacing all of the fake locations with ones pointing to the original function.

I am in full support for the new strategy of pointing to original function locations, so that it provides ease of debugging.

**Comment by vgvassilev** [comment]
I do not think the codecov complaint is relevant for this PR. Let's move forward.

**Pull request merged**
