### PR TITLE
fix: use clang++ in compilation commands

### LINKED ISSUE #530: Fix the Clad usage command in documentation.
Clad usage commands in Clad documentation ([https://clad.readthedocs.io/en/latest/user/InstallationAndUsage.html](https://clad.readthedocs.io/en/latest/user/InstallationAndUsage.html))  do not directly works. 
We should fix these commands and add more details/references explaining the command options.

### PR DESCRIPTION
**Pull request by snprajwal**
`clang` does not link the C++ standard libraries by default, causing it to fail on C++ files. Using `clang++` fixes this issue. The READMEs and examples in the `/demos` directory have been changed accordingly. There are also a couple of minor formatting fixes.

Edit: Fixes #530

### CODE REVIEW

**Review by parth-07 — APPROVED** [review]
Thank you for creating this pull request. LGTM.

**Comment by snprajwal** [comment]
This PR should also close #530 if I'm not wrong, linking the issue here for us to track

**Comment by vgvassilev** [comment]
Can you configure your editor to not trip white space automatically and undo all changes that are not relevant for the particular fix?

**Comment by snprajwal** [comment]
My editor seems to be giving me some trouble with this, please don't trigger the runs yet. Sorry for the multiple force pushes

**Comment by snprajwal** [comment]
It should be fixed now!

**Review by parth-07 — APPROVED** [review]
LGTM.

**Review by vgvassilev — APPROVED** [review]

**Pull request merged**
