### PR TITLE
Add CUDA 3D tensor contraction demo

### PR DESCRIPTION
**Pull request by kchristin22**

### CODE REVIEW

**Comment by vgvassilev** [comment]
Did you make sure that the output result is as expected?

**Comment by kchristin22** [comment]
Yes, I ran a python script using `torch` instead of Clad for the same set of inputs

**Comment by vgvassilev** [comment]
> Yes, I ran a python script using `torch` instead of Clad for the same set of inputs

Awesome! Great work!

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Pull request merged**
