### PR TITLE
Add the Arrays.cpp to the list of demos to run as tests.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@sudo-panda, can you look why these reference files fail?

**Comment by sudo-panda** [comment]
I have fixed the issue here: https://github.com/sudo-panda/clad/tree/add_arrays_to_demos

**Comment by vgvassilev** [comment]
> I have fixed the issue here: https://github.com/sudo-panda/clad/tree/add_arrays_to_demos
> 
> Should I open a new PR?

I picked up the commit from there - thanks!

**Comment by sudo-panda** [comment]
> > I have fixed the issue here: https://github.com/sudo-panda/clad/tree/add_arrays_to_demos
> > Should I open a new PR?
> 
> I picked up the commit from there - thanks!

I had changed your commit too you need to pick that change as well

**Comment by vgvassilev** [comment]
> > > I have fixed the issue here: https://github.com/sudo-panda/clad/tree/add_arrays_to_demos
> > > Should I open a new PR?
> > 
> > 
> > I picked up the commit from there - thanks!
> 
> I had changed your commit too you need to pick that change as well

Ok, let's close this one and go ahead and open yours.

**Pull request closed without merging**
