### PR TITLE
Run clang tidy check on PR

### PR DESCRIPTION
**Pull request by vaithak**

### CODE REVIEW

**Comment by vaithak** [comment]
cc :@Smit1603

**Comment by vaithak** [comment]
cc: @vgvassilev This is ready for review now.
Once this is merged, any warnings by clang-tidy will be visible as comments in the PR, examples can be seen here: https://github.com/marketplace/actions/clang-tidy-review.

Posting comments runs has a separate workflow which will only run once merged on master, as answered in the discussion here: https://github.com/orgs/community/discussions/25288

**Review by vgvassilev — APPROVED** [review]
Nicely done!

**Comment by vgvassilev** [comment]
Codecov does not trigger for some reason but I suspect that's ok for this PR.

**Pull request merged**
