### PR TITLE
Fix redefinition error in reverse mode(#138)

### PR DESCRIPTION
**Pull request by blide**

### CODE REVIEW

**Comment by blide** [comment]
Should I write a test for this? It seems like you have feature-oriented tests mostly

**Comment by vgvassilev** [comment]
Yes, we should add a test.

**Comment by vgvassilev** [comment]
Btw, is this PR in the context of GSoC?

**Comment by blide** [comment]
Yeah, it's

**Comment by vgvassilev** [comment]
> Yeah, it is

I would suggest contacting me in email asap.

**Comment by vgvassilev** [comment]
@blide, could you add a test for the particular issue and fix the failing test reference?

**Comment by blide** [comment]
@vgvassilev, done

**Comment by blide** [comment]
Interesting fact, functions listings in existing tests for hessian had redefinitions([here](https://github.com/vgvassilev/clad/pull/159/files#diff-02fb36ab56e5c50d869cbb0d93d99e63L28)), but it didn't cause an error.

For example
```c++
double f(double a, double c) {
    double _t1 = 1;
    return a*a*a*a*c*c + a*a*c*c*c*c;
}

  auto f_g = clad::gradient(f);
  f_g.dump();
//The code is: void f_grad(double a, double c, double *_result) {
//    double _d__t1 = 0;
//    double _t0;
//    double _t1;
//    double _t2;
//    double _t3;
//    double _t4;
//    double _t5;
//    double _t6;
//    double _t7;
//    double _t8;
//    double _t9;
//    double _t10;
//    double _t11;
//    double _t12;
//    double _t13;
//    double _t14;
//    double _t15;
//    double _t16;
//    double _t17;
//    double _t18;
//    double _t19;
//    double _t10 = 1; *redefinition*
```

While llvm IR for this function is:
```
  %a.addr = alloca double, align 8
  %c.addr = alloca double, align 8
  %_result.addr = alloca double*, align 8
  %_d__t1 = alloca double, align 8
  %_t0 = alloca double, align 8
  %_t1 = alloca double, align 8
  %_t2 = alloca double, align 8
  %_t3 = alloca double, align 8
  %_t4 = alloca double, align 8
  %_t5 = alloca double, align 8
  %_t6 = alloca double, align 8
  %_t7 = alloca double, align 8
  %_t8 = alloca double, align 8
  %_t9 = alloca double, align 8
  %_t10 = alloca double, align 8
  %_t11 = alloca double, align 8
  %_t12 = alloca double, align 8
  %_t13 = alloca double, align 8
  %_t14 = alloca double, align 8
  %_t15 = alloca double, align 8
  %_t16 = alloca double, align 8
  %_t17 = alloca double, align 8
  %_t18 = alloca double, align 8
  %_t19 = alloca double, align 8
  %_t101 = alloca double, align 8 *unique name*
```

So either clad dumps not exactly the function it produces, or llvm/clang fixes redefinitions for us

**Comment by vgvassilev** [comment]
Yes, the clang codegen is smart enough to avoid this issue but we are not guaranteed that would be the case in future.

**Comment by vgvassilev** [comment]
@efremale this PR looks good to me, can you take a look, too?

**Comment by efremale** [comment]
@blide, good idea, thanks for fixing this!

@vgvassilev, I am not 100% sure if it fixes all possible redefinition errors (may be, I don't have a counterexample in mind right now). This PR is a good fix anyway.

**Pull request merged**
