### PR TITLE
Add support for basic Kokkos operations in the rvs mode

### PR DESCRIPTION
**Pull request by gojakuch**

### CODE REVIEW

**Comment by vgvassilev** [comment]
If this is ready to review can you remove the draft status?

**Comment by gojakuch** [comment]
> If this is ready to review can you remove the draft status?

not really, I simply rebased it properly yesterday. I'll push some features and tests today and mark it as ready for review.

**Comment by gojakuch** [comment]
the failing check just can't find cmake files for some reason or smth like that

**Comment by vgvassilev** [comment]
> the failing check just can't find cmake files for some reason or smth like that

Was some network outage issue.

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Pull request merged**
