### PR TITLE
Ensure git-clang-format is run on PR

### LINKED ISSUE #537: Ensure the project follows `.clang-format`
Edit: Since there already is a `.clang-format` file, the project can be formatted in it's current state in a PR. This will reduce noise in future contributions and prevent incremental reformatting of the project files.

### PR DESCRIPTION
**Pull request by vaithak**
closes #537

### CODE REVIEW

**Comment by vgvassilev** [comment]
Can we also include the diff in the output of the bot so that people who don’t have it to know what’s wrong.

**Comment by vaithak** [comment]
> Can we also include the diff in the output of the bot so that people who don’t have it to know what’s wrong.

made changes to print colored diff 👍🏼

**Comment by vgvassilev** [comment]
Would the user be able to see on failure what commands to run to apply clang format so that it satisfies this build requirement?

**Comment by vaithak** [comment]
The command would be almost the same as what is being run for ci, the only difference being that ci runs with `--diff` argument which just shows what will be formatted instead of actually formatting the files.

**Comment by vgvassilev** [comment]
Let’s have that line in the ci after the error.

**Comment by vaithak** [comment]
updated 👍🏼

**Comment by vgvassilev** [comment]
Can we do the same for clang-tidy?

**Comment by vgvassilev** [comment]
@Smit1603 fyi.

**Pull request merged**
