### PR TITLE
Fix tests on i586

### LINKED ISSUE #792: Re-enable tests on i568
In PR #782 we have enabled support of 32 bit platforms and we have disabled many failing tests. Most of the failures are due to the fact that `sizeof` returns `unsigned int` on 32 bit and the test reference files require adjustment of that type:
`// CHECK-NEXT:     unsigned {{(int|long)}} _t2 = sizeof(double);`

### PR DESCRIPTION
**Pull request by MihailMihov**
resolves #792

This pull request currently fixes most of the tests, by changing them to expect either integers or longs, instead of just longs. The remaining tests are Gradient/Pointers, Misc/ClangConsumers and FirstDerivative/Overloads.

### CODE REVIEW

**Comment by MihailMihov** [comment]
Currently I'm trying to figure out why the clang invocation in Misc/ClangConsumers fails with `error: unknown FP unit 'sse'`, but debugging in a 32-bit chroot is difficult, because lldb just doesn't work[[1]](https://bugs.llvm.org/show_bug.cgi?id=45852). I also can't find any information about the bpf target in clang and whether an llvm toolchain built for i386 can target those cpus. This is the full command that the clang driver tries to execute:
`/usr/lib/llvm17/bin/clang-17 -cc1 -triple i386-alpine-linux-musl -emit-llvm -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name ClangConsumers.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -ffp-contract=on -fno-rounding-math -mfpmath sse -mconstructor-aliases -funwind-tables=2 -target-cpu pentium-m -debugger-tuning=gdb -v -fcoverage-compilation-dir=/root -resource-dir /usr/lib/llvm17/lib/clang/17 -I /root/clad/test/Misc/../../include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/i586-alpine-linux-musl/13.2.1/../../../../i586-alpine-linux-musl/include -internal-externc-isystem /usr/include/fortify -internal-externc-isystem /usr/include -internal-isystem /usr/lib/llvm17/lib/clang/17/include -fdebug-compilation-dir=/root -ferror-limit 19 -stack-protector 2 -fgnuc-version=4.2.1 -fcolor-diagnostics -add-plugin clad -load /root/clad/build/./lib/clad.so -debug-info-kind=limited -triple bpf-linux-gnu -target-cpu generic -print-stats -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o ClangConsumers.out -x c /root/clad/test/Misc/ClangConsumers.cpp`

It seems like the `-mfpmath sse` option is the one causing issues, but I don't see why that would be the case.

**Comment by MihailMihov** [comment]
The following command runs fine and build an executable that works:
```
alpine32:~# clang++ -Xclang -mfpmath -Xclang sse test.cpp
```
Adding `-triple bpf-linux-gnu -target-cpu generic` makes it fail:
```
alpine32:~# clang++ -Xclang -triple -Xclang bpf-linux-gnu -Xclang -target-cpu -Xclang generic -Xclang -mfpmath -Xclang sse test.cpp 
error: unknown FP unit 'sse'
```

**Comment by vgvassilev** [comment]
> Adding `-triple bpf-linux-gnu -target-cpu generic` makes it fail:
> 
> ```
> alpine32:~# clang++ -Xclang -triple -Xclang bpf-linux-gnu -Xclang -target-cpu -Xclang generic -Xclang -mfpmath -Xclang sse test.cpp 
> error: unknown FP unit 'sse'
> ```

Yes `bpf-linux-gnu` does not play well with `sse` on the bot. 

I suspect if you rebase your branch on top of the master the error probably will go away...

**Comment by vgvassilev** [comment]
> Currently I'm trying to figure out why the clang invocation in Misc/ClangConsumers fails with `error: unknown FP unit 'sse'`, but debugging in a 32-bit chroot is difficult, because lldb just doesn't work[[1]](https://bugs.llvm.org/show_bug.cgi?id=45852).

The should stay as an XFAIL.

**Comment by MihailMihov** [comment]
> > Currently I'm trying to figure out why the clang invocation in Misc/ClangConsumers fails with `error: unknown FP unit 'sse'`, but debugging in a 32-bit chroot is difficult, because lldb just doesn't work[[1]](https://bugs.llvm.org/show_bug.cgi?id=45852).
> 
> The should stay as an XFAIL.

Okay I'll keep the XFAIL in ClangConsumers.


For the other two tests what options do I have to debug them given that lldb doesn't work?

**Comment by MihailMihov** [comment]
Also I was having lots of problems with the tmate sessions in the CI and I set up a container with systemd-nspawn and an alpine i586 source root and it seems like a much better option for testing and debugging and identical to the CI environment. If you agree I could add a few paragraphs somewhere in the documentation detailing how to set it up?

**Comment by vgvassilev** [comment]
> Also I was having lots of problems with the tmate sessions in the CI and I set up a container with systemd-nspawn and an alpine i586 source root and it seems like a much better option for testing and debugging and identical to the CI environment. If you agree I could add a few paragraphs somewhere in the documentation detailing how to set it up?

Maybe somewhere in https://github.com/vgvassilev/clad/blob/master/docs/userDocs/source/user/DevelopersDocumentation.rst

**Comment by vgvassilev** [comment]
> > > Currently I'm trying to figure out why the clang invocation in Misc/ClangConsumers fails with `error: unknown FP unit 'sse'`, but debugging in a 32-bit chroot is difficult, because lldb just doesn't work[[1]](https://bugs.llvm.org/show_bug.cgi?id=45852).
> > 
> > 
> > The should stay as an XFAIL.
> 
> Okay I'll keep the XFAIL in ClangConsumers.
> 
> For the other two tests what options do I have to debug them given that lldb doesn't work?

What do you get for the others?

**Comment by MihailMihov** [comment]
> > > > Currently I'm trying to figure out why the clang invocation in Misc/ClangConsumers fails with `error: unknown FP unit 'sse'`, but debugging in a 32-bit chroot is difficult, because lldb just doesn't work[[1]](https://bugs.llvm.org/show_bug.cgi?id=45852).
> > > 
> > > 
> > > The should stay as an XFAIL.
> > 
> > 
> > Okay I'll keep the XFAIL in ClangConsumers.
> > For the other two tests what options do I have to debug them given that lldb doesn't work?
> 
> What do you get for the others?

Luckily gdb works even on i586, so now I'm trying to understand the backtrace from that. For Gradient/Pointers the code segfaults at the the following test:
```cxx
auto d_cStyleMemoryAlloc = clad::gradient<clad::opts::disable_tbr>(cStyleMemoryAlloc, "x");
  d_x = 0;
  d_cStyleMemoryAlloc.execute(5, 7, &d_x);
  printf("%.2f\n", d_x); // CHECK-EXEC: 4.00
```
Freeing the `p` pointer in `cStyleMemoryAlloc` is the one that leads to the segfault. ([bt -full](https://pastebin.com/Mj1Kxpkf))

**Comment by vgvassilev** [comment]
You should rebase your PR because the master changed significantly how clad works and the backtrace can be irrelevant.

**Comment by vgvassilev** [comment]
If that’s ready to review please remove the draft status of this pr.

**Comment by MihailMihov** [comment]
> If that’s ready to review please remove the draft status of this pr.

Even after the rebase the Gradient/Pointers and FirstDerivative/Overloads tests are still failing, so I'll try to get some new backtraces and try to get them working. The rest of the tests should be good, so I'll remove the draft status. Also according to the documentation of lit UNSUPPORTED should be used to mark tests that are not supported for a certain environment, so maybe we should change XFAIL to UNSUPPORTED?

**Comment by vgvassilev** [comment]
I think that `Gradient/Pointers` and `FirstDerivative/Overloads` can go in a separate PR so that this one goes forward. Can you improve the commit message mentioning `Fixes #<issue number>`?

**Review by vgvassilev — APPROVED** [review]
LGTM!

In interest of making progress here I'd suggest to open a new issue for the remaining two failures on 32 bit. Another slightly more challenging issue to look into is #428.

**Pull request merged**
