### PR TITLE
Fix benchmark comparison in ci

### PR DESCRIPTION
**Pull request by vaithak**

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
Thank you! LGTM!

**Comment by vgvassilev** [comment]
@vaithak, looks like when it went in the master it failed with: https://github.com/vgvassilev/clad/actions/runs/5960281839/job/16167325061

**Comment by vaithak** [comment]
yup, I tried to ssh into tmate for that action, but it didn't allow me to, maybe because of access related to master branch. 
Will try to ssh into a PR branch and see what's going wrong. 

I have found the issue, but need to figure out why that happened.
The problem is that `git rev-parse HEAD` is outputting `HEAD` instead of the commit id, this only happens when HEAD is in a detached state.

**Comment by vgvassilev** [comment]
If you tried to do ssh via the web browser it does not work for me either. If you ssh via the terminal you need to type `ctrl+c` to get to a prompt. I can restart the same build if you want to retry.

**Comment by vaithak** [comment]
I tried with terminal only, it gave me `Permission denied (publickey)` error.

**Comment by vgvassilev** [comment]
I logged in, could you retry?

**Comment by vaithak** [comment]
> I logged in, could you retry

trying

**Comment by vaithak** [comment]
still got the same error of `Permission denied (publickey)`.
I am able to access `ssh -T git@github.com` so there should be no error with the keys setup.

**Pull request merged**
