### PR TITLE
Update osx builds in ci to cover both x86 and arm

### PR DESCRIPTION
**Pull request by mcbarton**
@vgvassilev  This PR updates the osx part of the CI to have fixed version numbers, and adds osx arm builds.

### CODE REVIEW

**Comment by mcbarton** [comment]
@vgvassilev can you rerun the ci for me please?

**Comment by vgvassilev** [comment]
> @vgvassilev can you rerun the ci for me please?

Done.

**Comment by mcbarton** [comment]
@vgvassilev can you rerun the ci for me? I've made another attempt at fixing the linking issue on osx arm, and added a runtime17 build for Windows.

**Comment by mcbarton** [comment]
@vgvassilev this PR is ready for review.

**Review by alexander-penev — APPROVED** [review]

**Pull request merged**
