### PR TITLE
Improve derived variable init for const pointers

### PR DESCRIPTION
**Pull request by vaithak**
This will fix the segmentation fault in roofit benchmarks (when auxiliary arrays are removed).

### CODE REVIEW

**Comment by vaithak** [comment]
cc: @guitargeek. I have tested this with the atlas likelihood benchmark code, it now works after removing the auxiliary arrays. The runtime results have also improved because of this.

**Comment by vaithak** [comment]
The issue was that while calling pullbacks, we don't maintain non-differentiable arguments. @PetroZarytskyi  had fixed this for most of the cases here: <https://github.com/vgvassilev/clad/pull/802>, but it still had some more complex cases which required activity analysis, as he mentioned in the PR too.
My PR just tries to improve upon that by handling the case for const pointers, which can be handled without activity analysis too.

**Review by vgvassilev — COMMENTED** [review]
LGTM but I'd wait for @PetroZarytskyi's review.

**Comment by PetroZarytskyi** [comment]
Looks good to me. Sure, this will probably become obsolete once we have activity analysis but this is a great simplification for now.

**Pull request merged**
