### PR TITLE
Add support for `std::array` in the fwd mode

### PR DESCRIPTION
**Pull request by gojakuch**
Fixes: #829

### CODE REVIEW

**Comment by vgvassilev** [comment]
Can we add support in reverse mode before closing the issue?

**Comment by gojakuch** [comment]
> Can we add support in reverse mode before closing the issue?

I'll see if it's possible. should be.

**Comment by parth-07** [comment]
> I'll see if it's possible. should be.

It would be difficult because we don't support custom derivatives of member functions and constructors in the reverse mode...

**Comment by parth-07** [comment]
@vgvassilev A long time ago, you suggested creating a separate repository to maintain custom derivatives. I liked that idea because custom derivatives can grow a lot. What do you think about that idea now?

**Comment by vgvassilev** [comment]
> @vgvassilev A long time ago, you suggested creating a separate repository to maintain custom derivatives. I liked that idea because custom derivatives can grow a lot. What do you think about that idea now?

Yes, however, the challenge would be keeping it in sync with the changes of clad and making it more difficult for clad to introduce backward incompatible changes. That being said we should do this but probably for libraries like Stl and a few others that represent major usecases for us we should keep those in the repo…

**Comment by parth-07** [comment]
> Yes, however, the challenge would be keeping it in sync with the changes of clad and making it more difficult for clad to introduce backward incompatible changes.

Yes, agreed...

> That being said we should do this but probably for libraries like Stl and a few others that represent major usecases for us we should keep those in the repo…

Okay, this sounds good.

**Comment by gojakuch** [comment]
> > I'll see if it's possible. should be.
> 
> It would be difficult because we don't support custom derivatives of member functions and constructors in the reverse mode...

oh, for some reason I thought this works. not so possible to hit this in this PR then

**Comment by vgvassilev** [comment]
> > > I'll see if it's possible. should be.
> > 
> > 
> > It would be difficult because we don't support custom derivatives of member functions and constructors in the reverse mode...
> 
> oh, for some reason I thought this works. not so possible to hit this in this PR then

Then open another issue for std::array support in reverse mode then.

**Review by vgvassilev — APPROVED** [review]
Lgtm!

**Pull request merged**
