### PR TITLE
Remove dependency of how the fn is passed to clad diff functions

### PR DESCRIPTION
**Pull request by parth-07**
Currently clad update calls like these:
```c++
auto d_fn_1 = clad::differentiate(freeFn, ...);
auto d_fn_2 = clad::differentiate(&freeFn, ...);
auto d_memFn = clad::differentiate(&SomeClass::SomeMethod, ...);
```
to
```c++
auto d_fn_1 = clad::differentiate(derivedFn, ...);
auto d_fn_2 = clad::differentiate(&derivedFn, ...);
auto d_memFn = clad::differentiate(&SomeClass::SomeMethodDerivedFn, ...);
```

While updating arguments, `&` is only added to the derived fn argument, if `&` was originally present. To achieve this behaviour clad have to find the relevant parent of fn argument `DeclRefExpr`, then act differently depending on if the relevant parent found was `UnaryOperator` or some cast. 

We can instead always add `&` with the derived fn argument. 
This way we will not need to keep track of whether the most recent parent was `ImplicitCastExpr` or `UnaryOperator`, we will not need to differentiate the 2 cases. And this will have no other change in AST other than `ImplicitCastExpr` changed to `UnaryOperator` in fn arguments of clad differentiation calls, since as per clad implementation, function types are always decomposed to function pointer types while passing them to clad differentiation functions.

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
Good job! Can you squash the two commits and copy the PR description as a commit message? I guess we cannot make codecov happy here for some reason but that's ok.

**Comment by parth-07** [comment]
@vgvassilev Thank you for approving the PR, but if we decide to go with passing function/functor argument by universal reference in my other PR ([#240](https://github.com/vgvassilev/clad/pull/240)) then that will do similar work as done here and will overwrite the work done in this PR. Should we wait to merge this PR until we come to a conclusion regarding passing function/functor argument by universal reference or not ?

**Comment by vgvassilev** [comment]
@parth-07, okay, let's wait. Could you update the description of the other PR to capture the design, intent and the proposed solution?

**Comment by parth-07** [comment]
@vgvassilev I have updated the PR description to include more details.

**Comment by vgvassilev** [comment]
@parth-07, what is the fate of this PR?

**Comment by parth-07** [comment]
Its fate depends on one design decision that we have to decide in PR #240. That design decision is, should we pass function/functor by universal reference or not. We need to pass functors by reference otherwise we cannot detect `constness` attribute. Should I convert this PR to draft in the meantime? 

Given the recent developments, PR #240 needs some modifications and can be made simpler. I will make those modifications and rebase #240 on top of the master branch so it will be easier to review.

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by vgvassilev** [comment]
The codecov complaint is coming from removing code which reduces the coverage compared to previous master but that's what we want -- less code.

**Pull request merged**
