### PR TITLE
Recover the testsuite run with clang built in debug mode

### PR DESCRIPTION
**Pull request by vgvassilev**
This PR fixes several problems with clad's testsuite when ran with clang built in debug mode.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@grimmmyshini, can you take a look at this PR?

**Review by grimmmyshini — COMMENTED** [review]
I think it looks good. However, some of the tests are canceled on the CI. Is that intentional?

**Comment by vgvassilev** [comment]
> I think it looks good. However, some of the tests are canceled on the CI. Is that intentional?

Yes, see #476

**Comment by vgvassilev** [comment]
The negative codecov report is expected as I have added a stack protection assertion in `getUnderlyingArrayType`.

**Pull request merged**
